####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 244
  unit_system: imperial
  time_zone: !secret time_zone
  whitelist_external_dirs:
    - /config
    - /share

####################################################
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
####################################################

#https://home-assistant.io/docs/configuration/splitting_configuration/
automation: !include_dir_merge_list automation/
cloud: !include cloud.yaml
frontend: !include frontend.yaml
ios: !include ios.yaml
notify: !include notification.yaml
recorder: !include recorder.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/

####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

#https://home-assistant.io/components/config/
config:

#https://www.home-assistant.io/hassio/
hassio:

#https://home-assistant.io/components/history/
history:

#https://home-assistant.io/components/http/
http:

#https://home-assistant.io/components/logger/
logger:
  default: error

#https://www.home-assistant.io/lovelace/yaml-mode/
lovelace:
  mode: yaml
  resources:
    #https://github.com/MizterB/lovelace-secondaryinfo-entity-row
    - url: /local/secondaryinfo-entity-row.js
      type: module
    #https://github.com/thomasloven/lovelace-card-tools
    - url: /local/card-tools.js?v=9
      type: js
    #https://github.com/custom-cards/vertical-stack-in-card
    - url: /local/vertical-stack-in-card.js
      type: js
    #https://github.com/maykar/custom-header
    - url: /local/custom-header.js
      type: module
  dashboards:
    reserved-ips:
      mode: yaml
      filename: lovelace-reservedips.yaml
      title: Reserved IPs
      icon: mdi:lan
      show_in_sidebar: true
      require_admin: true

#https://www.home-assistant.io/integrations/mobile_app/
mobile_app:

#https://home-assistant.io/components/sun/
sun:

#https://www.home-assistant.io/integrations/google_translate/
tts:
  - platform: google_translate

#https://www.home-assistant.io/integrations/zone/
zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 750

  - name: Adam Work
    latitude: !secret adam_work_latitude
    longitude: !secret adam_work_longitude
    radius: 350

  - name: Amy Work
    latitude: !secret amy_work_latitude
    longitude: !secret amy_work_longitude
    radius: 350

####################################################
#               BINARY SENSOR                      #
####################################################

#https://home-assistant.io/components/binary_sensor.ping/
binary_sensor:
  - platform: ping
    host: 192.168.100.1
    name: Modem

####################################################
#                     COVER                        #
####################################################
#https://www.home-assistant.io/components/opengarage/
cover:
  platform: opengarage
  covers:
      garage:
        host:  192.168.1.18
        device_key: !secret device_key
        name: Garage Door

####################################################
#                 INPUT BOOLEAN                    #
####################################################

#https://home-assistant.io/components/input_boolean/
input_boolean:
  vacation:
    name: Vacation Mode
    initial: off
  guest:
    name: Guest Mode
    initial: off
  feeddog:
    name: feeddog
    initial: off
  doorbelllight:
    name: doorbelllight
    initial: off

####################################################
#                    INPUT SELECT                  #
####################################################

#https://home-assistant.io/components/input_select/
input_select:
  notification_bulb2_color:
    options:
      - "Normal"
      - "White"
      - "Red"
      - "Orange"
      - "Yellow"
      - "Green"
      - "Blue"
      - "Indigo"
      - "Violet"
      - "Purple"
    icon: mdi:lightbulb
    initial: White

####################################################
#                     LIGHT                        #
####################################################

#https://www.home-assistant.io/components/light.group/
light:
  - platform: group
    name: Front Lights
    entities:
      - light.yeelight1
      - light.yeelight3
      - light.yeelight4

  - platform: group
    name: Bedroom Lights
    entities:
      - light.tradfri_bulb_e26_ws_opal_980lm_2_2
      - light.tradfri_bulb_e26_ws_opal_980lm_3

  - platform: group
    name: Basement Lights
    entities:
      - light.zooz_zen27_s2_dimmer_wall_switch_level
      - light.zooz_zen27_s2_dimmer_wall_switch_level_2
      - light.zooz_zen27_s2_dimmer_wall_switch_level_3

####################################################
#                   SPEEDTEST                      #
####################################################

#https://www.home-assistant.io/components/speedtestdotnet/
speedtestdotnet:
  server_id: 1776
  monitored_conditions:
    - download
    - upload

####################################################
#                TRADFRI HUB                       #
####################################################

#https://home-assistant.io/components/tradfri/
tradfri:
  host: 192.168.1.20
  allow_tradfri_groups: false

####################################################
#                   WEATHER                        #
####################################################

#https://www.home-assistant.io/components/weather.darksky/
weather:
  - platform: darksky
    api_key: !secret darksky
    mode: daily

####################################################
#                     YEELIGHTS                    #
####################################################

#https://home-assistant.io/components/light.yeelight/
yeelight:
  devices:
    192.168.1.10:
      name: Yeelight1
    192.168.1.11:
      name: Yeelight2
    192.168.1.12:
      name: Yeelight3
    192.168.1.26:
      name: Yeelight4
    192.168.1.28:
      name: Yeelight5
    192.168.1.25:
      name: YeelightRGB2

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
