#########################################################
#                                                       #
#         NOTIFY DESKTOP PC TURNED ON AND AWAY          #
#                                                       #
#########################################################

  - alias: "DESKTOP PC ON WHEN AWAY"
    initial_state: true
    trigger:
      platform: state
      entity_id: switch.desktop_switch
      from: 'off'
      to: 'on'
    condition:
        condition: template
        value_template: "{{ states('person.adam') != 'home' }}"
    action:
      service: notify.home_assistant
      data:
        title: "Desktop PC turned on"
        message: "Desktop PC was turned on and Adam is not home"

#########################################################
#                                                       #
#                 FAILED LOGIN ATTEMPTS                 #
#                                                       #
#########################################################

  - alias: "Send notification upon failed login attempt"
    initial_state: true
    trigger:
      - platform: state
        entity_id: persistent_notification.http_login
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'None' }}"
    action:
      - service: notify.home_assistant
        data_template:
          title: "{{ states.persistent_notification.http_login.attributes.message }}"
          message: 'url: https://whatismyipaddress.com/ip/{{ states.persistent_notification.http_login.attributes.message.split ("from ") [1]}}'
      - service: persistent_notification.dismiss
        data:
          notification_id: 'http_login'

#########################################################
#                                                       #
#            END OF CONFIGURATION FILE                  #
#                                                       #
#########################################################
